# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
np.__version__

'2.2.4'

#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
vector1 = np.zeros(10)
vector1, vector1.shape

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), (10,))

#### 4. How to find the memory size of any array (★☆☆)

In [11]:
vector1.size, vector1.shape

(10, (10,))

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
np.add.__doc__

"add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])\n\nAdd arguments element-wise.\n\nParameters\n----------\nx1, x2 : array_like\n    The arrays to be added.\n    If ``x1.shape != x2.shape``, they must be broadcastable to a common\n    shape (which becomes the shape of the output).\nout : ndarray, None, or tuple of ndarray and None, optional\n    A location into which the result is stored. If provided, it must have\n    a shape that the inputs broadcast to. If not provided or None,\n    a freshly-allocated array is returned. A tuple (possible only as a\n    keyword argument) must have length equal to the number of outputs.\nwhere : array_like, optional\n    This condition is broadcast over the input. At locations where the\n    condition is True, the `out` array will be set to the ufunc result.\n    Elsewhere, the `out` array will retain its original value.\n    Note that if an uninitialized `out` array is created via the defau

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [14]:
vector2 = np.zeros(10)
vector2[4] = 1
vector2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [226]:
vector3 = np.arange(10,50)
vector3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [18]:
vector3[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [23]:
mat1 = np.arange(0,9)
mat1 = mat1.reshape(3,3)
mat1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [50]:
vector4 = np.array([1,2,0,0,4,0])
indices = np.nonzero(vector4)
indices

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [52]:
mat2 = np.eye(3,3)
mat2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [55]:
mat3 = np.random.randint(0,1000,(3,3))
mat3

array([[ 61, 510,  62],
       [590, 747, 747],
       [237, 839, 848]], dtype=int32)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [56]:
mat4 = np.random.randint(0,1000,(10,10))
mat4.max(), mat4.min()

(np.int32(997), np.int32(3))

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [57]:
vector6 = np.random.randint(0,10000,30)
vector6.mean()

np.float64(4728.933333333333)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [74]:
mat6 = np.zeros((5,5))
accepted = [mat6.shape[0]-1,0]
for i in range(len(mat6)):
    for j in range(len(mat6[0])):
        if i in accepted or j in accepted:
            mat6[i][j] = 1
mat6

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [75]:
mat6 = np.ones((5,5))
accepted = [mat6.shape[0]-1,0]
for i in range(len(mat6)):
    for j in range(len(mat6[0])):
        if i in accepted or j in accepted:
            mat6[i][j] = 0
mat6

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [190]:
np.nan, False, False, np.nan, True, True, False

(nan, False, False, nan, True, True, False)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [106]:
mat8 = np.arange(0,25)
mat8 = mat8.reshape((5,5))
mat8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [107]:
fill_below = np.diag(mat8,-1)
np.fill_diagonal(mat8,fill_below)

In [108]:
mat8

array([[ 5,  1,  2,  3,  4],
       [ 5, 11,  7,  8,  9],
       [10, 11, 17, 13, 14],
       [15, 16, 17, 23, 19],
       [20, 21, 22, 23,  5]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [135]:
mat9 = np.zeros((8,8))
mat9

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [136]:
mat9[1::2,::2] = 1
mat9[::2,1::2] = 1

In [137]:
mat9

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [151]:
mat10 = np.arange(0,336).reshape((6,7,8))

In [159]:
flatten_index = 100
shape = (6,7,8)
index1 = flatten_index/(shape[-1])
index2 = flatten_index/(shape[-2])
index3 = flatten_index/(shape[-3])

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [176]:
mat11 = np.array([[0,1,0,1],[1,0,1,0]])
mat11

array([[0, 1, 0, 1],
       [1, 0, 1, 0]])

In [182]:
np.tile(mat11,(4,2))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [184]:
mat12 = np.random.randint(0,10000,(5,5))
mat12

array([[2016,  392, 7427, 2081, 5642],
       [3881, 4190, 6400, 2482, 6405],
       [3178, 1655, 5108, 1554, 8847],
       [ 949, 9336, 3678, 9573, 1805],
       [2514, 8085, 9225, 2519, 6463]], dtype=int32)

In [191]:
def normalize(arr):
    arr = arr - arr.min()
    arr = arr/ (arr.max()-arr.min())
    return arr

In [192]:
normalize(mat12)

array([[0.17688705, 0.        , 0.7662564 , 0.18396689, 0.57183313],
       [0.38002396, 0.41368043, 0.65439495, 0.22764405, 0.65493955],
       [0.30345278, 0.13756671, 0.51366953, 0.12656573, 0.92092365],
       [0.06066877, 0.97418582, 0.35791308, 1.        , 0.1539048 ],
       [0.23112951, 0.83792615, 0.96209563, 0.23167411, 0.66125694]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [199]:
COLOR = np.dtype([('R',np.ubyte),('G',np.ubyte),('B',np.ubyte),('A',np.ubyte)])

In [200]:
image = np.empty((1),dtype=COLOR)

In [201]:
image

array([(221, 35, 0, 0)],
      dtype=[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [203]:
mat13 = np.random.randint(0,1000,(5,3))
mat14 = np.random.randint(0,1000,(3,2))

In [204]:
np.dot(mat13,mat14)

array([[533650, 709478],
       [838991, 864378],
       [809458, 787011],
       [912442, 994956],
       [732612, 985434]], dtype=int32)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [206]:
vector7 = np.arange(0,10)
vector7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
vector7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [219]:
9, 10

(9, 10)

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [247]:
"Z**Z", "2 << Z >> 2", "Z <- Z", "1j*Z", "Z/1/1"

('Z**Z', '2 << Z >> 2', 'Z <- Z', '1j*Z', 'Z/1/1')

In [248]:
'Only the last option is not legal.'

'Only the last option is not legal.'

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [12]:
print(np.nan, np.int64(0), np.array([np.nan]).astype(int).astype(float))

nan 0 [-9.22337204e+18]


C:\Users\yatha\AppData\Local\Temp\ipykernel_31184\3477701471.py:1: RuntimeWarning: invalid value encountered in cast
  print(np.nan, np.int64(0), np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [9]:
float_array = np.array([1.2, -1.2, 2.5, -2.5, 3.7, -3.7])

rounded_array = np.array([np.ceil(i) if i > 0 else np.floor(i) for i in float_array])

print("Original array:", float_array)
print("Rounded array:", rounded_array)

Original array: [ 1.2 -1.2  2.5 -2.5  3.7 -3.7]
Rounded array: [ 2. -2.  3. -3.  4. -4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [10]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

common_values = np.intersect1d(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("Common values:", common_values)

Array 1: [1 2 3 4 5]
Array 2: [4 5 6 7 8]
Common values: [4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [15]:
import warnings

warnings.filterwarnings("ignore")

array = np.array([1, 2, 3])
result = np.divide(array, 0)

print("Result:", result)

Result: [inf inf inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [16]:
np.sqrt(-1) == np.emath.sqrt(-1)

np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [20]:
today = np.datetime64('today')

yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2025-04-01
Today: 2025-04-02
Tomorrow: 2025-04-03


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [22]:
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')

july_dates = np.arange(start_date, end_date, dtype='datetime64[D]')

print("Dates in July 2016:")
print(july_dates)


Dates in July 2016:
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [23]:
A = np.array([1, 2, 3], dtype=float)
B = np.array([4, 5, 6], dtype=float)

A += B

A *= -A / 2

print("Result:", A)


Result: [-12.5 -24.5 -40.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [26]:
random_array = np.random.random(10) * 100
print("Original array:", random_array)

integer_part_floor = np.floor(random_array)
print("Integer part (using np.floor):", integer_part_floor)

integer_part_trunc = np.trunc(random_array)
print("Integer part (using np.trunc):", integer_part_trunc)

integer_part_astype = random_array.astype(int)
print("Integer part (using astype(int)):", integer_part_astype)

integer_part_round = np.round(random_array, decimals=0).astype(int)
print("Integer part (using np.round):", integer_part_round)

Original array: [14.28617031 52.34389162 37.11601146  3.81825106 59.40291199 84.98483719
 50.03486863 70.33004617 19.80567096 28.24168005]
Integer part (using np.floor): [14. 52. 37.  3. 59. 84. 50. 70. 19. 28.]
Integer part (using np.trunc): [14. 52. 37.  3. 59. 84. 50. 70. 19. 28.]
Integer part (using astype(int)): [14 52 37  3 59 84 50 70 19 28]
Integer part (using np.round): [14 52 37  4 59 85 50 70 20 28]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [406]:
matrix = np.random.randint(0,4,(5,5))
matrix

array([[0, 1, 3, 3, 0],
       [0, 0, 3, 1, 2],
       [2, 3, 1, 1, 1],
       [1, 1, 3, 0, 1],
       [0, 3, 1, 2, 2]], dtype=int32)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [409]:
def integer_generator():
    for i in range(10):
        yield i

generated_array = np.array(list(integer_generator()))

print("Generated array:", generated_array)

Generated array: [0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [411]:
vector = np.linspace(0, 1, 12)[1:-1]

print("Vector:", vector)

Vector: [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [414]:
random_vector = np.random.random(10)

sorted_vector = np.sort(random_vector)

print("Original vector:", random_vector)
print("Sorted vector:", sorted_vector)

Original vector: [0.44780748 0.64542484 0.99833822 0.78769429 0.14043971 0.18269964
 0.59588498 0.06600722 0.94472512 0.22903363]
Sorted vector: [0.06600722 0.14043971 0.18269964 0.22903363 0.44780748 0.59588498
 0.64542484 0.78769429 0.94472512 0.99833822]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [416]:
small_array = np.array([1, 2, 3, 4, 5])

fast_sum = sum(small_array)

numpy_sum = np.sum(small_array)

print("Sum using built-in sum():", fast_sum)
print("Sum using np.sum():", numpy_sum)

Sum using built-in sum(): 15
Sum using np.sum(): 15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [421]:
A = np.random.random(10)
B = np.random.random(10)

are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)
print("Are A and B equal?", are_equal)

Array A: [0.00271075 0.08902944 0.81591182 0.70302555 0.76288026 0.31607746
 0.0837769  0.22091105 0.71347565 0.95962486]
Array B: [0.42606948 0.57701646 0.03711874 0.48834616 0.24137841 0.20795436
 0.70895617 0.96416358 0.25783396 0.31753567]
Are A and B equal? False


#### 43. Make an array immutable (read-only) (★★☆)

In [422]:
array = np.array([1, 2, 3, 4, 5])

array.flags.writeable = False

try:
    array[0] = 10
except ValueError as e:
    print("Error:", e)

print("Array:", array)

Error: assignment destination is read-only
Array: [1 2 3 4 5]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [426]:
cartesian = np.random.random((10, 2)) * 10
print("Cartesian coordinates (x, y):")
print(cartesian)

x = cartesian[:, 0]
y = cartesian[:, 1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

polar = np.column_stack((r, theta))
print("\nPolar coordinates (r, theta):")
print(polar)

Cartesian coordinates (x, y):
[[0.68872891 9.33669882]
 [2.40859727 9.64755435]
 [8.47601825 4.05539533]
 [1.14346293 3.29480254]
 [6.64696988 0.87598029]
 [2.94989185 8.23809503]
 [0.50308952 0.41477063]
 [3.5570867  0.35282386]
 [9.66948717 3.77798488]
 [7.18765074 5.50053828]]

Polar coordinates (r, theta):
[[ 9.36206667  1.4971639 ]
 [ 9.94367366  1.32613878]
 [ 9.39622886  0.44626372]
 [ 3.48758244  1.23675152]
 [ 6.70444256  0.13103132]
 [ 8.75031837  1.22694206]
 [ 0.65202281  0.68947089]
 [ 3.574542    0.09886561]
 [10.38133671  0.37247395]
 [ 9.05086982  0.65320643]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [425]:
random_vector = np.random.random(10) * 100
print("Original vector:", random_vector)

max_index = np.argmax(random_vector)

random_vector[max_index] = 0

print("Modified vector:", random_vector)

Original vector: [12.4517071  84.61001435 58.33194762 74.59074869  6.89897327 73.07804087
 36.87387462 95.81066862 66.04483335 26.79481329]
Modified vector: [12.4517071  84.61001435 58.33194762 74.59074869  6.89897327 73.07804087
 36.87387462  0.         66.04483335 26.79481329]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [427]:
grid_size = 10

x = np.linspace(0, 1, grid_size)
y = np.linspace(0, 1, grid_size)

xx, yy = np.meshgrid(x, y)

structured_array = np.zeros(xx.shape, dtype=[('x', float), ('y', float)])
structured_array['x'] = xx
structured_array['y'] = yy

print("Structured array:")
print(structured_array)

Structured array:
[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.3

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [430]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

C = 1 / (X[:, np.newaxis] - Y[np.newaxis, :])

print("Cauchy matrix:")
print(C)

Cauchy matrix:
[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [431]:
print("Integer types:")
for dtype in [np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__}: min={info.min}, max={info.max}")

print("\nFloating-point types:")
for dtype in [np.float16, np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype.__name__}: min={info.min}, max={info.max}, eps={info.eps}")


Integer types:
int8: min=-128, max=127
int16: min=-32768, max=32767
int32: min=-2147483648, max=2147483647
int64: min=-9223372036854775808, max=9223372036854775807
uint8: min=0, max=255
uint16: min=0, max=65535
uint32: min=0, max=4294967295
uint64: min=0, max=18446744073709551615

Floating-point types:
float16: min=-65504.0, max=65504.0, eps=0.0009765625
float32: min=-3.4028234663852886e+38, max=3.4028234663852886e+38, eps=1.1920928955078125e-07
float64: min=-1.7976931348623157e+308, max=1.7976931348623157e+308, eps=2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [435]:
large_array = np.arange(100)
print("Array with all values:")
print(large_array)

Array with all values:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [436]:
vector = np.array([1, 3, 8, 10, 15, 20])
scalar = 12

closest_index = np.argmin(np.abs(vector - scalar))

closest_value = vector[closest_index]

print("Vector:", vector)
print("Scalar:", scalar)
print("Closest value:", closest_value)


Vector: [ 1  3  8 10 15 20]
Scalar: 12
Closest value: 10


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)